[package]
name = "bmk_mgr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27"
ratatui = "0.26"
rusqlite = "0.31"
itertools = "0.12.1"
unicode-width = "0.1"
fakeit = "1.2"
