[package]
name = "rust-workbench"
version = "0.1.0"
edition = '2024'
authors = ["slbtty<shenlebantongying@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="main"
path= "main.rs"
