[package]
name = "rust_general"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"


[[bin]]
name="ubc"
path="src/unbound_chan.rs"


[[bin]]
name="asc"
path="src/async_io.rs"
