[package]
name = "rust_general"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = { version = "0.3" }

[[bin]]
name = "unbound_chan"
path = "src/unbound_chan.rs"

[[bin]]
name = "async_io"
path = "src/async_io.rs"

[[bin]]
name = "arc_basis"
path = "src/arc_basis.rs"
