[package]
name = "tree"
version = "0.1.0"
authors = ["slbtty<shenlebantongying@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[[bin]]
name="bvew"
path= "tree/biggest_value_each_row.rs"
