[package]
name = "druid_gui_test"
version = "0.1.0"
authors = ["shenleban tongying <shenlebantongying@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = { git = "https://github.com/linebender/druid.git" }

[[bin]]
name = "grid_four"
path = "src/grid_four.rs"
